---
name: Build de l'image Docker
kind: pipeline
type: exec
steps:
- name: Creation de l'image Builder
  commands:
    - docker-compose -f docker-compose-builder.yml build
    - docker-compose -f docker-compose-builder.yml up

- name: Création de l'image site
  commands:
    - docker-compose build 

- name: Connexion au registre Docker personnel
  commands : 
    - runuser -l root -c "echo $docker_registry_pass | docker login -u $docker_registry_user --password-stdin registry.thoughtless.eu"
    - runuser -l root -c "echo $docker_registry_pass | docker login -u $docker_registry_user --password-stdin docker.thoughtless.eu"
  environment:
    docker_registry_pass:
      from_secret: docker_registry_pass
    docker_registry_user:
      from_secret: docker_registry_user

- name: Televersement de l'image sur le registre
  commands :
    - runuser -l root -c "cd $PWD && docker-compose push"

---
name: CD ! 
kind: pipeline
type: ssh
server:
  host:
    from_secret: ip_cd
  user: root
  ssh_key:
    from_secret: ssh_key
depends_on:
  - "Build de l'image Docker"

steps:
- name: Connexion au registre Docker personnel
  commands : 
  - echo $docker_registry_pass | docker login -u $docker_registry_user --password-stdin registry.thoughtless.eu
  - echo $docker_registry_pass | docker login -u $docker_registry_user --password-stdin docker.thoughtless.eu
  environment:
    docker_registry_pass:
      from_secret: docker_registry_pass
    docker_registry_user:
      from_secret: docker_registry_user

- name: Arret des conteneurs actuels
  commands: 
  - docker stop cyberprez01 | echo '0'
  - docker rm cyberprez01 | echo '0'  

- name: Déploiement du conteneur via docker-compose
  commands: 
  - "docker-compose pull"
  - "docker-compose up -d "
